# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="JNEYSTADT"


inherit perl-module

DESCRIPTION="Convert::Cyrillic v1.02 - Routines for converting from one cyrillic charset to another."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 amd64 ~amd64-linux"
IUSE=""

DEPEND="dev-perl/Unicode-Map8
	dev-perl/Unicode-String
	dev-lang/perl"
