# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.0

EAPI="2"

MODULE_AUTHOR="MSERGEANT"

inherit perl-module

MY_P="CDB_File-${PV}"

DESCRIPTION="Tie to CDB (Bernstein's constant DB) files"
SRC_URI="http://search.cpan.org/CPAN/authors/id/M/MS/MSERGEANT/${MY_P}.tar.gz"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~x86 x86"
IUSE=""

S="${WORKDIR}/${MY_P}"
