--- GNUmakefile.orig	2008-07-02 01:27:38.000000000 +0300
+++ GNUmakefile	2008-07-02 01:31:28.000000000 +0300
@@ -25,13 +25,11 @@
 .PHONY:all
 all: $(addsuffix .install,$(SPECIALS)) meld.desktop
 	$(MAKE) -C po
-	$(MAKE) -C help
 
 .PHONY:clean
 clean: 
 	-rm -f *.pyc *.install meld.desktop *.bak glade2/*.bak
 	$(MAKE) -C po clean
-	$(MAKE) -C help clean
 
 .PHONY:install
 install: $(addsuffix .install,$(SPECIALS)) meld.desktop
@@ -43,8 +41,7 @@
 		$(DESTDIR)$(docdir_) \
 		$(DESTDIR)$(sharedir)/applications \
 		$(DESTDIR)$(sharedir)/application-registry \
-		$(DESTDIR)$(sharedir)/pixmaps \
-		$(DESTDIR)$(helpdir_)
+		$(DESTDIR)$(sharedir)/pixmaps
 	install -m 755 meld.install \
 		$(DESTDIR)$(bindir)/meld
 	install -m 644 *.py \
@@ -69,7 +66,6 @@
 	install -m 644 glade2/pixmaps/icon.png \
 		$(DESTDIR)$(sharedir)/pixmaps/meld.png
 	$(MAKE) -C po install
-	$(MAKE) -C help install
 
 meld.desktop: meld.desktop.in
 	intltool-merge -d po meld.desktop.in meld.desktop
@@ -78,7 +74,6 @@
 	$(PYTHON) tools/install_paths \
 		libdir=$(libdir_) \
 		localedir=$(localedir) \
-		helpdir=$(helpdir_) \
 		sharedir=$(sharedir_) \
 		< $< > $@
 
@@ -87,13 +82,11 @@
 	-rm -rf \
 		$(sharedir_) \
 		$(docdir_) \
-		$(helpdir_) \
 		$(libdir_) \
 		$(bindir)/meld \
 		$(sharedir)/applications/meld.desktop \
 		$(sharedir)/pixmaps/meld.png
 	$(MAKE) -C po uninstall
-	$(MAKE) -C help uninstall
 
 .PHONY: test
 test:
