--- Makefile.orig	2008-09-24 21:59:06.000000000 +0300
+++ Makefile	2008-09-24 22:05:16.000000000 +0300
@@ -52,7 +52,7 @@
 
 CC        = gcc
 CPP       = g++
-LIBTOOL   = libtool
+LIBTOOL   = libtool --tag CC
 INSTALL   = install
 
 BCOP      = `pkg-config --variable=bin bcop`
