#!/bin/sh

OPTIONS="--initramfs-overlay=/usr/share/v86d --menuconfig"

kernel=`eselect kernel show|grep gentoo|awk -F/ '{print $NF}'`

kernel=${kernel#linux-}
arch=`arch`

echo "Kernel version: $kernel"

genkernel $OPTIONS all
#emerge @module-rebuild
module-rebuild -X rebuild

echo "Generating initramfs with dracut"
dracut --force "/boot/initramfs-genkernel-$arch-$kernel" $kernel

update-burg

#Add to kernel options: video=uvesafb:1600x1200-32@60,mtrr:3,ywrap
