#!/bin/sh

OPTIONS="--initramfs-overlay=/usr/share/v86d --menuconfig"

kernel=`eselect kernel show|grep gentoo|awk -F/ '{print $NF}'`

kernel=${kernel#linux-}
arch=`arch`

echo "Kernel: $kernel"
echo "Arch:   $arch"

genkernel $OPTIONS all
#emerge @module-rebuild
module-rebuild -X rebuild

echo "Generating initramfs with dracut"
dracut --force "/boot/initramfs-genkernel-$arch-$kernel" $kernel

update-grub

