#!/bin/sh


OPTIONS="--initramfs-overlay=/usr/share/v86d --menuconfig --plymouth --no-fbsplash"

kernel=`eselect kernel show|grep gentoo|awk -F/ '{print $4}'`
kernel=${kernel#linux-}
arch=`arch`

echo "Kernel version: $kernel"

echo "Generating initramfs with dracut"
dracut --force "/boot/initramfs-genkernel-$arch-$kernel" $kernel

update-burg

#Add to kernel options: video=uvesafb:1600x1200-32@60,mtrr:3,ywrap