# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="KMELTZ"


inherit perl-module

DESCRIPTION="Manage Unix crypt-style password file."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 amd64 ~amd64-linux"
IUSE=""

DEPEND=">=dev-perl/Digest-SHA1-2.130.0
	dev-perl/Crypt-PasswdMD5
	dev-lang/perl"
