# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="ROODE"


inherit perl-module

DESCRIPTION="Companion module for Time::Format, to speed up time formatting."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 amd64 ~amd64-linux"
IUSE=""

DEPEND=">=perl-gcpan/Time-Format-1.11
	dev-lang/perl"
