EAPI=2

DESCRIPTION="Runtime libs for autopro"
HOMEPAGE=""
SLOT="0"

LICENSE="|| ( LGPL-2.1 GPL-3 )"
KEYWORDS="~alpha ~amd64 ~arm ~ia64 ~ppc ~ppc64 ~x86 ~amd64-linux ~x86-linux ~ppc-macos ~x86-macos ~x64-solaris ~x86-solaris"

DEPEND=""
RDEPEND="
dev-perl/Apache-Session
dev-perl/Archive-Zip
dev-perl/BerkeleyDB
dev-perl/Bit-Vector
dev-perl/BSD-Resource
dev-perl/Cache
dev-perl/Cache-Cache
dev-perl/Cache-Memcached
dev-perl/Cache-Memcached-Fast
dev-perl/CDB_File
dev-perl/Class-Factory-Util
dev-perl/Crypt-Blowfish
dev-perl/crypt-cbc
dev-perl/Crypt-SSLeay
dev-perl/Data-Dump
dev-perl/Date-Calc
dev-perl/DateManip
dev-perl/DBD-mysql
dev-perl/DBI
dev-perl/Digest-SHA1
dev-perl/Email-Address
dev-perl/Error
dev-perl/FCGI
dev-perl/File-NFSLock
dev-perl/Font-AFM
dev-perl/GD
dev-perl/Geo-IP
dev-perl/Graphics-ColorNames
dev-perl/Heap
dev-perl/HTML-Format
dev-perl/HTML-Parser
dev-perl/HTML-Tagset
dev-perl/HTML-Tree
dev-perl/HTTP-Cookies
dev-perl/IO-Socket-SSL
dev-perl/IO-stringy
dev-perl/IPC-ShareLite
dev-perl/JSON
dev-perl/LockFile-Simple
dev-perl/MailTools
dev-perl/Math-Round
dev-perl/MIME-Lite
dev-perl/MIME-tools
dev-perl/Moose
dev-perl/NetAddr-IP
dev-perl/Net-DNS
dev-perl/Net-Domain-TLD
dev-perl/Net-SSLeay
dev-perl/Params-Validate
dev-perl/Proc-ProcessTable
dev-perl/Spreadsheet-WriteExcel
dev-perl/string-crc32
dev-perl/Sys-MemInfo
dev-perl/Term-ProgressBar
dev-perl/Text-Aspell
dev-perl/Text-CSV
dev-perl/Text-CSV_XS
dev-perl/Text-Iconv
dev-perl/Tie-IxHash
dev-perl/TimeDate
dev-perl/Unicode-Map8
dev-perl/Unicode-String
dev-perl/URI
dev-perl/URI-Fetch
dev-perl/WWW-Mechanize
dev-perl/WWW-Mechanize-FormFiller
dev-perl/XML-DOM
dev-perl/XML-Dumper
dev-perl/XML-Generator
dev-perl/XML-NamespaceSupport
dev-perl/XML-Parser
dev-perl/XML-RegExp
dev-perl/XML-SAX
dev-perl/XML-Simple
dev-perl/YAML-Tiny
perl-gcpan/Apache-Htpasswd
perl-gcpan/base
perl-gcpan/Class-AutoAccess
perl-gcpan/cyrillic
perl-gcpan/Data-Serializer
perl-gcpan/Data-Validate-Domain
perl-gcpan/Data-Validate-Email
perl-gcpan/DumpStack
perl-gcpan/File-Touch
perl-gcpan/HTML-DOMbo
perl-gcpan/Math-Approx
perl-gcpan/Math-Matrix
perl-gcpan/Object-MultiType
perl-gcpan/Sys-CpuLoad
perl-gcpan/Text-ExtractWords
perl-gcpan/Text-xSV
perl-gcpan/Tie-DBI
perl-gcpan/Time-Format
perl-gcpan/Time-Format_XS
perl-gcpan/WWW-Mechanize-Cached
perl-gcpan/XML-Smart
virtual/perl-Data-Dumper
virtual/perl-Encode
perl-gcpan/GD-SecurityImage
media-gfx/imagemagick
"

pkg_postinst() {
	echo
	elog "Please note that this meta package is only provided for convenience."
	echo
}

