#!/bin/sh

kernel=`eselect kernel show|grep gentoo|awk -F/ '{print $NF}'`
kernel=${kernel#linux-}
arch=`arch`

echo "Kernel version: $kernel"

echo "Generating initramfs with dracut"
dracut --force "/boot/initramfs-genkernel-$arch-$kernel" $kernel

update-grub

#Add to kernel options: video=uvesafb:1600x1200-32@60,mtrr:3,ywrap