# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.13.02

inherit perl-module

S=${WORKDIR}/Test-MockObject-1.07
DESCRIPTION="No description available."
SRC_URI="mirror://cpan/authors/id/C/CH/CHROMATIC/Test-MockObject-1.07.tar.gz"
HOMEPAGE="http://www.cpan.org/modules/by-authors/id/C/CH/CHROMATIC/${P}.readme"

IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="alpha amd64 arm hppa ia64 m68k mips ppc ppc64 ppc-macos s390 sh sparc sparc-fbsd x86 x86-fbsd"

DEPEND="perl-core/Scalar-List-Utils
	dev-perl/Test-Exception
	perl-gcpan/UNIVERSAL-isa
	perl-gcpan/UNIVERSAL-can
	dev-perl/module-build
	perl-core/Test-Simple"

