# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="RGARCIA"


inherit perl-module

DESCRIPTION="Establish an ISA relationship with base classes at compile time"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 amd64 ~amd64-linux"
IUSE=""

DEPEND="dev-lang/perl"
