# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.0

EAPI="2"

MODULE_AUTHOR="HMBRAND"

inherit perl-module
MY_P="Text-CSV_XS-${PV}"

DESCRIPTION="Fast 8bit clean version of Text::CSV"
SRC_URI="http://search.cpan.org/CPAN/authors/id/H/HM/HMBRAND/${MY_P}.tgz"


LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~x86 x86"
IUSE=""

DEPEND="dev-lang/perl"


S="${WORKDIR}/${MY_P}"